### ISSUE TITLE
Minor name suggestion: change from "obfuscate" to "obscure"

### ISSUE THREAD

**Issue by msheller** [anishathalye/obfuscated-gradients#13]
The security community is primed to react negatively to "security through obscurity". Based on my experience, calling gradient masking/obfuscation "gradient obscuring" actually communicates the problem to security researchers more quickly. May seem silly, but jargon matters, especially when evangelizing research across disciplines.

**Comment by carlini** [comment]
Anish and I talked at length about whether we wanted to use obfuscate or obscure. We decided to go with obfuscate for a few reasons. In large parts, this goes back to the question of why we called it something different than gradient masking.

To me, the use of "obfuscate" implies some form of imposed obscurity. In contrast with some prior defenses that had shown evidence of gradient masking through various methods, all of these methods that we broke had blocking gradient signal either as a direct goal, or as something that may not have been intentional but was a direct consequence of the design. (For example, thermometer encoding did not set out to block the gradient signal, but by construction, it did.)

Given this, we chose the word obfuscate to give some hint towards what we believed as the cause of these defenses appearing to be effective. The dictionary tells me the definition of obfuscate is "render obscure, unclear, or unintelligible". I believe that accurately captures what is being done by these defenses.

I'm not quite sure what you're arguing with people reacting negatively to "security through obscurity" when we use the word "obfuscate" -- it seems like that would be an argument against using the word "obscure".

**Comment by msheller** [comment]
My preference for "obscurity" comes from its overlap with jargon in the security field. Implying negativity is intentional: I think it's a correct mental leap for security researchers to hear about gradient-masking and relate it to "security-through-obscurity" because gradient-masking doesn't work if the attackers know the model is using it. I believe both terms are plenty precise, so I would choose between them based on the effects they have on those who hear them. Clearly, I'm biased toward terms that help communication with security folks :)

**Comment by anishathalye** [comment]
I'm going to close this issue, partly because we can't change the name of our paper. I think obscure and obfuscated both have their merits. And now, we have papers with wordings: our [Obfuscated Gradients Give a False Sense of Security: Circumventing Defenses to Adversarial Examples](https://arxiv.org/abs/1802.00420), which defines "obfuscated gradients", and [Adversarial Risk and the Dangers of Evaluating Against Weak Attacks](https://arxiv.org/abs/1802.05666), which uses the term "obscured models". I think the meanings are slightly different, though: in our paper, we're talking about a specific type of gradient masking that we call obfuscated gradients, while in the paper by Uesato et al., I think they're using "obscured models" to refer to security through obscurity in general (whether or not it's achieved through obfuscated gradients).
