### ISSUE TITLE
Unfolding optimization process DefenseGAN

### ISSUE THREAD

**Issue by dmh43** [anishathalye/obfuscated-gradients#14]
Hi, thank you for sharing your code! I am very excited about the results of this paper -- it's been a very informative read.

I'm trying to reproduce the results of partially attacking DefenseGAN on MNIST and am having some trouble figuring out at which point in the code that is happening. The notebook in that directory seems to just attack a classifier using the l2 attack rather than the whole defensegan process. For example, i cant figure out where the projection step is happening. Am i missing something?

Thanks again for your help!

**Comment by carlini** [comment]
The DefenseGAN code we have is the break of the "perfect" version of this classifier. In particular, what it's doing is given an image X, it is searching for a x so that |G(z)-X| is small but g(Z) is adversarial. So the projection step is built into the fact that we're searching over z's.

**Comment by carlini** [comment]
So the idea of the DefenseGAN defense is that given an image X, it wants to search for a value of z that minimizes |G(z)-X|. Since we restrict our adversarial examples to be only those where there exists a z* so that X=G(z*), a "perfect" implementation of DefenseGAN would recover this value z* exactly. And so this operation is sound.

You're right, of course, that because the defense is performed with SGD in practice, this does not occur. We describe this in the paper, too, and is why we report a 55% success for this defense instead of 0%.
